### ISSUE TITLE
Never say "shortly"

### ISSUE THREAD

**Issue by troyibm** [hoppa12/Flutter-TTS-Service#1]
Is your definition of "shortly" around 5 months?  :)

Just joking with you really, cause this is exactly what happens when I write something like "check back soon for X" and X never gets done.

Honestly, it's a bummer that TTS and STT aren't supported in flutter.io by now.

**Comment by hoppa12** [comment]
thank you!

I actually seen a pub package of TTS released shortly after my release, so that made it non viable to continue this really

https://pub.dartlang.org/packages/tts

**Comment by hoppa12** [comment]
By the way if you are an enthusiast of TTS in general, check out my extension for the Yandex Browser for Android

https://github.com/hoppa12/TTS-For-Yandex-Android

I am only a newbie developer, so I gave up on Flutter. I only wrote that plugin because I too found it ridiculous that it was not available and thought some might find it useful.

Thanks for stopping by, "Shortly" edited!
